language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

env:
  - DB=mysql

matrix:
    include:
        - php: 5.6
          env: DB=postgres
        - php: 5.6
          env: DB=sqlite
    allow_failures:
        - php: hhvm

dist: trusty

sudo: false

cache:
  directories:
    - vendors
    - $HOME/.composer/cache

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} =~ ^7\.[234]$ ]] ; then pear config-set preferred_state snapshot && yes "" | pecl install mcrypt ; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - |
    bash -c "if [[ '${TRAVIS_PHP_VERSION:0:3}' =~ ^7\.4$ ]]; then
    sudo add-apt-repository ppa:ondrej/php;
    sudo apt update;
    sudo apt-get install php7.4-gd;
    echo "extension = gd.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
    fi;"
  - |
    bash -c "if [ '$DB' == 'mysql' ]; then
    mysql -u root -e \"CREATE DATABASE basercms CHARACTER SET utf8;\";
    mysql -u root -e \"GRANT ALL PRIVILEGES ON basercms.* TO basercms@localhost IDENTIFIED BY 'basercms';\";
    fi;"
  - |
    bash -c "if [ '$DB' == 'postgres' ]; then
    psql -U postgres -c \"CREATE USER basercms WITH PASSWORD 'basercms';\";
    psql -U postgres -c \"CREATE DATABASE basercms OWNER basercms ENCODING='utf8'\";
    fi;"
  - composer self-update;
  - if [ -n "$GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;
  - composer install;
  - cd app
  - php ./Console/cake.php bc_manager checkenv

notifications:
  email: false
